### ISSUE TITLE
github.com/pebbe/util.IsTerminal failing on Go 1.5rc1

### ISSUE THREAD

**Issue by srid** [heroku/log-shuttle#52]
```
spew | log-shuttle -verbose -skip-verify -logs-url=http://...snip... -logplex-token=`cat run.token`
panic: Not implemented

goroutine 1 [running]:
github.com/heroku/log-shuttle/Godeps/_workspace/src/github.com/pebbe/util.IsTerminal(0x820648008, 0x820622640)
	/Users/sratnakumar/go/src/github.com/heroku/log-shuttle/Godeps/_workspace/src/github.com/pebbe/util/isterminal.go:15 +0x65
main.useStdin(0x2710)
	/Users/sratnakumar/go/src/github.com/heroku/log-shuttle/cmd/log-shuttle/main.go:32 +0x23
main.main()
	/Users/sratnakumar/go/src/github.com/heroku/log-shuttle/cmd/log-shuttle/main.go:222 +0x167
^C2015/08/10 17:14:38 Received interrupt; sending annotation to librato...
2015/08/10 17:14:38 ERROR sending to librato: Librato config not set
make: *** [run-stream] Error 2


```

**Comment by freeformz** [comment]
@srid I use log-shuttle on osx all the time. How did you build log-shuttle? What version of go?

**Comment by srid** [comment]
Ah, this only happens with Go 1.5rc1. Not on the stable version.

**Comment by freeformz** [comment]
This is likely do to changes in CGO support. I'll have to play around and/or maybe patch pebbe utils stuff to DTRT for osx (if possible, which I assume it is).
